### ISSUE TITLE
[Suggestion] Provide .withState() that can set a CustomState

### ISSUE THREAD

**Issue by avenmore** [AlexJPotter/fluentvalidation-ts#14]
This feature is very useful in the [FluentValidation C# library](https://docs.fluentvalidation.net/en/latest/custom-state.html) as it allows categorisation of applied rules, for e.g., into errors or warnings. Of course the ValidationError results would become more complex so as to provide a message and possible additional data.

**Comment by AlexJPotter** [comment]
Hi there - thanks for your suggestion 😄 

As you've pointed out, this feature would require quite a substantial change to the `ValidationErrors` object, which I'm keen to avoid at this time (I have been thinking about how I can expose more information on `ValidationErrors` while maintaining backwards compatibility, but I haven't made any decisions just yet).

For the use-case you've mentioned (warnings vs errors), I would perhaps create two separate validators for the same class - one to serve up warnings and the other to serve up errors. For example:

```typescript
type User = { name: string; emailAddress: string };

class UserErrorValidator extends Validator<User> {
  constructor() {
    super();
    this.ruleFor('name')
      .notEmpty()
      .withMessage('Please enter your name');
  }
}

class UserWarningValidator extends Validator<User> {
  constructor() {
    super();
    this.ruleFor('emailAddress')
      .notEmpty()
      .withMessage('You will not receive notifications if you do not provide an email address');
  }
}

const errorValidator = new UserErrorValidator();
const warningValidator = new UserWarningValidator();

const user: User = { name: 'Alex', emailAddress: '' };

const errors = errorValidator.validate(user);
const warnings = warningValidator.validate(user);
```

I'm going to close this issue for now, but I'll definitely consider this suggestion when thinking about how to make `ValidationErrors` more powerful.

**Comment by avenmore** [comment]
Thanks very much for considering it. I adopted two strategies to handle this; one, almost exactly as your example above demonstrates, and two (if I have control over where it will be used), to prefix a message with an identifier, e.g. '[warn] This will be needed later'.
Really appreciate this library as I'm able to create matching client-side rules for my C# back-end - thanks again :)
