### ISSUE TITLE
Export ValueValidationResult

### ISSUE THREAD

**Issue by jp-rl** [AlexJPotter/fluentvalidation-ts#41]
Hi Alex,

First of all, thanks for your library and the work you have invested in it. I usually use Fluent Validation in .net so it was a great surprise to find your library and use it in typescript.

I need to import the ValueValidationResult type for certain cascading validations inside nested components.

Before (v2.3.0) you could import from node_modules/fluentvalidation-ts/dist, but now (v3.1.0) in dist there is only index.d.ts

Could you consider exporting Value ValidationResult in dist/index.d.ts in future versions?

export { AsyncValidator, ValidationErrors, SyncValidator as Validator, ValueValidationResult };

TIA! Regards

**Comment by AlexJPotter** [comment]
Hi @jp-rl - apologies for the delay on this. I've just released [v.3.2.0](https://github.com/AlexJPotter/fluentvalidation-ts/releases/tag/v3.2.0) that includes the desired type export. Please let me know if you have any further issues 🙂
