### ISSUE TITLE
Validation rule for two properties

### ISSUE THREAD

**Issue by rwb196884** [AlexJPotter/fluentvalidation-ts#42]
I have an object
```
{
  a: number, 
  b: number
}
```

How do I write a validaton rule to require `a + b <= 100`?

**Comment by bohoffi** [comment]
@rwb196884 you could use a [custom rule](https://fluentvalidation-ts.alexpotter.dev/docs/guides/customrules#:~:text=The%20predicate%20function%20can%20also%20depend%20on%20the%20value%20of%20the%20model%20as%20well%20as%20the%20value%20of%20the%20property%3A) to achieve this.

```ts
this.ruleFor('a').must(
  (a, model) => a + model.b <= 100
);
```

**Comment by AlexJPotter** [comment]
Hi @rwb196884, the answer provided by @bohoffi is correct (thank you!)
