### ISSUE TITLE
Validate "array of objects" property in a class

### ISSUE THREAD

**Issue by newvision-sam** [AlexJPotter/fluentvalidation-ts#8]
Issue: Can't find a way of validating objects in a ReadonlyArray property of an object.

- Using this.ForEach('packages') yields the following error: "Argument of type '"packages"' is not assignable to parameter of type 'never'"

- Ideal solution: this.ruleForEach('packages').must(value => value.weight.grams < 1000);

**Comment by AlexJPotter** [comment]
Hi, thanks for bringing this to my attention - the types are currently set up to work with properties that are a standard `Array`, but they don't handle `ReadonlyArray` properties at the moment. I'll look at fixing this :thumbsup:

**Comment by AlexJPotter** [comment]
This issue should be fixed in version 2.2.1 - thanks again for pointing it out 😃

**Comment by newvision-sam** [comment]
Thanks Alex!
